const express = require('express');
const { body, validationResult } = require('express-validator');
const nodemailer = require('nodemailer');
const logger = require('../services/logger');
const { registerUser, loginUser, requestPasswordReset, resetPassword, findUserByEmail } = require('../services/postgresAuth');
const { authenticate, clearAuthCookies, extractAccessToken, extractSessionCookie } = require('../middleware/postgresAuth');
const { logoutSession } = require('../services/session.service.pg');
const env = require('../config/env');
const { limiterLogin } = require('../middleware/rateLimit');
const router = express.Router();
const errors = (req) => validationResult(req).array()[0]?.msg || 'Datos inválidos';
const passwordRules = body('password').isString().isLength({min:6}).withMessage('Contraseña: mínimo 6 caracteres');
router.post('/register', limiterLogin, [body('email').isEmail().normalizeEmail().withMessage('Email inválido'), passwordRules, body('confirm_password').custom((v,{req}) => { if(v !== req.body.password) throw new Error('Las contraseñas no coinciden'); return true; })], async (req,res) => {
  const e=validationResult(req); if(!e.isEmpty()) return res.status(400).json({ok:false,message:errors(req)});
  try { const parts=String(req.body.name || `${req.body.first_name || ''} ${req.body.last_name || ''}`).trim().split(/\s+/); const user=await registerUser({first_name:String(req.body.first_name||parts[0]||'').trim(),last_name:String(req.body.last_name||parts.slice(1).join(' ')).trim(),email:req.body.email,password:req.body.password}); const logged=await loginUser(user.email,req.body.password,req,res); return res.status(201).json({ok:true,message:'Registro exitoso',user:logged,redirect:'/dashboard.html'}); }
  catch(err) { if(err.code==='23505') return res.status(409).json({ok:false,message:'El email ya está registrado'}); logger.error('[auth] register',err); return res.status(500).json({ok:false,message:'Error interno'}); }
});
router.post('/login', limiterLogin, [body('email').isEmail().normalizeEmail().withMessage('Email inválido'),body('password').isString().isLength({min:1}).withMessage('Contraseña requerida')], async(req,res)=>{ const e=validationResult(req); if(!e.isEmpty()) return res.status(400).json({ok:false,message:errors(req)}); try { const user=await loginUser(req.body.email,req.body.password,req,res); if(!user) return res.status(401).json({ok:false,message:'Email o contraseña incorrectos'}); return res.json({ok:true,message:'Sesión iniciada',user,redirect:user.role==='admin'?'/admin/dashboard.html':'/dashboard.html'}); } catch(err){ logger.error('[auth] login',err); return res.status(500).json({ok:false,message:'Error interno'}); }});
router.post('/logout', authenticate, async(req,res)=>{ await logoutSession(req.authSessionId); clearAuthCookies(res); res.json({ok:true,message:'Sesión cerrada correctamente',redirect:'/login.html'}); });
router.get('/me', authenticate, (req,res)=>res.json({ok:true,user:req.user}));
router.post('/forgot-password', limiterLogin, [body('email').isEmail().normalizeEmail().withMessage('Email inválido')], async(req,res)=>{ const e=validationResult(req); if(!e.isEmpty()) return res.status(400).json({ok:false,message:errors(req)}); try { const token=await requestPasswordReset(req.body.email); if(token){ const url=`${env.PASSWORD_RESET_URL}?access_token=${encodeURIComponent(token)}`; if(env.SMTP_HOST&&env.SMTP_USER&&env.SMTP_PASSWORD&&env.SMTP_FROM){ const transporter=nodemailer.createTransport({host:env.SMTP_HOST,port:env.SMTP_PORT,secure:env.SMTP_PORT===465,auth:{user:env.SMTP_USER,pass:env.SMTP_PASSWORD}}); await transporter.sendMail({from:env.SMTP_FROM,to:req.body.email,subject:'Restablecer contraseña - Narel Local',text:`Abrí este enlace para cambiar tu contraseña: ${url}`}); } else logger.info(`[auth] Reset URL (${req.body.email}): ${url}`); } return res.json({ok:true,message:'Si el email se encuentra registrado, te enviaremos las instrucciones para restablecer la contraseña.'}); } catch(err){ logger.error('[auth] forgot',err); return res.json({ok:true,message:'Mail de recuperación enviado (si aplica)'}); }});
router.post('/reset-password', [body('new_password').isString().isLength({min:6}).withMessage('Nueva contraseña debe tener al menos 6 caracteres'),body('confirm_password').custom((v,{req})=>{if(v!==req.body.new_password) throw new Error('Las contraseñas no coinciden');return true;})], async(req,res)=>{ const e=validationResult(req); if(!e.isEmpty()) return res.status(400).json({ok:false,message:errors(req)}); const token=req.body.access_token||req.query.access_token; if(!token) return res.status(400).json({ok:false,message:'Token de recuperación faltante'}); try { const ok=await resetPassword(token,req.body.new_password); if(!ok) return res.status(400).json({ok:false,message:'El link expiró o es inválido, pedí uno nuevo'}); return res.json({ok:true,message:'Contraseña actualizada correctamente. Ahora podés iniciar sesión con tu nueva clave.',redirect:'/login.html'}); } catch(err){logger.error('[auth] reset',err);return res.status(500).json({ok:false,message:'Error interno'});} });
module.exports=router;
